In [2]:
import numpy as np

## Basic

In [3]:
# 1. Write a NumPy program to get the numpy version and show numpy build configuration
print(np.version)
print(np.show_config)

<module 'numpy.version' from '/usr/lib64/python3.10/site-packages/numpy/version.py'>
<function show at 0x7f307c22c9d0>


In [4]:
# 2. Write a NumPy program to  get help on the add function
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [7]:
# 3. Write a NumPy program to test whether none of the elements of a given array is zero
a = np.array([0, 1, 2, 3])
np.all(a)

True

In [12]:
# 4. Write a NumPy program to test whether any of the elements of a given array is non-zero. 
a = np.array([0, 1, 0])
np.any(a)

True

In [15]:
# 5. Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a Number).
a = np.array([1, 0, np.nan, np.inf])
np.isfinite(a)

array([ True,  True, False, False])

In [17]:
# 6. Write a NumPy program to test element-wise for positive or negative infinity.
a = np.array([1, 0, np.nan, np.inf])
np.isposinf(a)
np.isneginf(a)

array([False, False, False, False])

In [18]:
# 7. Write a NumPy program to test element-wise for NaN of a given array.
a = np.array([1, 0, np.nan, np.inf])
np.isnan(a)

array([False, False,  True, False])

In [19]:
# 8. Write a NumPy program to test element-wise for complex number, 
# real number of a given array. Also test whether a given number is a scalar type or not.
a = np.array([1, 0, np.nan, np.inf])
np.iscomplex(a)
np.isreal(a)
np.isscalar(a)

False

In [25]:
# 9. Write a NumPy program to test whether two arrays are element-wise equal within a tolerance. 
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])

np.allclose(a, b)

True

In [29]:
# 10. Write a NumPy program to create an element-wise comparison
# (greater, greater_equal, less and less_equal) of two given arrays.
a = np.array([1, 5, 4])
b = np.array([1, 4, 2])

np.greater(a,b)
np.greater_equal(a,b)
np.less(a,b)
np.less_equal(a,b)

array([ True, False, False])

In [30]:
# 11. Write a NumPy program to create an element-wise comparison
# (equal, equal within a tolerance) of two given arrays.
a = np.array([1, 5, 4])
b = np.array([1, 4, 2])

np.equal(a, b)
np.allclose(a,b)

False

In [35]:
# 12. Write a NumPy program to create an array with the values 1, 7, 13, 105
# and determine the size of the memory occupied by the array.
a = np.array([1, 7, 13, 105])
np.size(a)
print(f"{a.size * a.itemsize} bytes")

32 bytes


In [42]:
# 13. Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.
a = np.zeros(10)
a = np.ones(10)
a = np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [47]:
# 14. Write a NumPy program to create an array of the integers from 30 to 70
np.arange(30,71,1)

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

In [48]:
# 15. Write a NumPy program to create an array of all the even integers from 30 to 70.
np.arange(30, 71, 2)

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

In [56]:
# 16. Write a NumPy program to create a 3x3 identity matrix.
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [75]:
# 17. Write a NumPy program to generate a random number between 0 and 1.
np.random.normal(0,1,1)

array([0.55448092])

In [78]:
# 18. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution. 
np.random.normal(0,1,15)

array([ 0.44466085,  0.03392839, -0.30088667, -0.64913455,  0.3874986 ,
        0.29999823,  1.00892662, -1.53158642, -0.3481902 , -0.15182416,
       -1.00502073, -0.34198242, -0.09378281, -1.08937996,  0.7573188 ])

In [81]:
# 19. Write a NumPy program to create a vector with values ranging from 15
# to 55 and print all values except the first and last.
a = np.arange(15, 56)
a[1:-1]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54])

In [90]:
# 20. Write a NumPy program to create a 3X4 array using and iterate over it.
np.arange(10,22).reshape((3, 4))

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])